### PR TITLE
Added Sort and Logout button

### PR DESCRIPTION
**Pull request by yuneihlaing**
- Got sort to work with username.
- The tasks should remain sorted when you add, filter, or edit the tasks until you click on the 'Remove sort' button. 
- Clicking on the logout button should take you to the login page 
- Edited the findTaskByCategoryandUsername function in the task-services file so filter works now.

### CODE REVIEW

**Review by dustint121 — APPROVED** [review]
No merge conflicts. Nice!

**Review by jubenjam — APPROVED** [review]
LGTM

**Review by CameronBill — APPROVED** [review]
Looks good to me, and I saw the date sorting. Very snappy.

**Comment by arigoodmann22** [comment]
looks good!

**Pull request merged**
