### PR TITLE
Users can now change between Log In and Sign Up page

### PR DESCRIPTION
**Pull request by arigoodmann22**

### CODE REVIEW

**Review by CameronBill — APPROVED** [review]
Glad it's working. LGTM!

**Review by jubenjam — APPROVED** [review]
LGTM

**Review by yuneihlaing — APPROVED** [review]
Looks good!

**Review by dustint121 — COMMENTED** [review]
Code looks good. Feel free to merge once everyone reviewed code.

**Review by dustint121 — APPROVED** [review]
Looks good!

**Pull request merged**
